SectionVerb {
	Value {
		TQ "HiFi"
	}

	EnableSequence [
		cset "name='DAC In Mux' 'Normal Path'"
		cset "name='Lineout Volume' 4,4"
	]
}

SectionDevice."Speaker" {
	Comment "Internal speaker"

	EnableSequence [
		cset "name='Ext_Amp_Force_Mute' on"
		cset "name='LOL Mux' 'Playback'"
		cset "name='ADDA_DL_CH1 DL1_CH1' on"
		cset "name='ADDA_DL_CH2 DL1_CH2' on"
		cset "name='Ext_Speaker_Amp Switch' on"
		cset "name='Ext_Amp_Force_Mute' off"
	]

	DisableSequence [
		cset "name='Ext_Amp_Force_Mute' on"
		cset "name='Ext_Speaker_Amp Switch' off"
		cset "name='ADDA_DL_CH1 DL1_CH1' off"
		cset "name='ADDA_DL_CH2 DL1_CH2' off"
		cset "name='LOL Mux' 'Open'"
	]

	Value {
		PlaybackPriority 100
		PlaybackPCM "hw:mt6789mt6366,0"
		PlaybackChannels 2
	}
}
